version: "3.7"
services:
  api_service:
    build: .
    ports:
      - 8080:8080
    networks:
      - springapimysql-net
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/communityInfo?allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_USERNAME=root
    depends_on:
      - mysqldb

    volumes:
      - .m2:/root/.m2

  mysqldb:
    image: "mysql"
    ports:
      - 3308:3306
    networks:
      - springapimysql-net
    environment:
      MYSQL_DATABASE: communityInfo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
networks:
  springapimysql-net: